# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-02 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_APP', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
